// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK45EaFGNudHBHBUGmrpTPrT2zz26Ny9I',
    appId: '1:195809586850:web:9f42b32be6804bda9ef1fb',
    messagingSenderId: '195809586850',
    projectId: 'nexahome-d9d03',
    authDomain: 'nexahome-d9d03.firebaseapp.com',
    storageBucket: 'nexahome-d9d03.firebasestorage.app',
    measurementId: 'G-RWSVYVJ3HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKovntdZE01vimlnMOZr8dhzyZDMjFEiI',
    appId: '1:195809586850:android:7dc8f6ca31a1b36e9ef1fb',
    messagingSenderId: '195809586850',
    projectId: 'nexahome-d9d03',
    storageBucket: 'nexahome-d9d03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2E7CSgkS0zzQmc3s1y8rBmGDDw_d09Yo',
    appId: '1:195809586850:ios:59f69f26b5bc81ab9ef1fb',
    messagingSenderId: '195809586850',
    projectId: 'nexahome-d9d03',
    storageBucket: 'nexahome-d9d03.firebasestorage.app',
    iosBundleId: 'com.geekflow.homeAutomation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2E7CSgkS0zzQmc3s1y8rBmGDDw_d09Yo',
    appId: '1:195809586850:ios:ce0993075187a8d99ef1fb',
    messagingSenderId: '195809586850',
    projectId: 'nexahome-d9d03',
    storageBucket: 'nexahome-d9d03.firebasestorage.app',
    iosBundleId: 'com.example.homefi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDK45EaFGNudHBHBUGmrpTPrT2zz26Ny9I',
    appId: '1:195809586850:web:72019dc412db6dd79ef1fb',
    messagingSenderId: '195809586850',
    projectId: 'nexahome-d9d03',
    authDomain: 'nexahome-d9d03.firebaseapp.com',
    storageBucket: 'nexahome-d9d03.firebasestorage.app',
    measurementId: 'G-9YFHV64203',
  );
}
